### ISSUE TITLE
Переместить в ingenerkateam.

### ISSUE THREAD

**Issue by nm17** [IngenerkaTeamCenter1/PreMotorService#1]
У нас уже есть организация. Переместите 2 этих прототипа туда.

**Comment by mabramovsd** [comment]
Не всё так просто. Велик риск, что в центре и Заволжье будет одинаковая задача. Ну и репозитории будут называться похожим образом. В общем, получится не тру

**Comment by nm17** [comment]
А может создать для них разные ветки? 

Edit: и ещё команды для них. И все в одной организации. 

Edit 2: можно ещё также и права разграничить.

**Comment by mabramovsd** [comment]
Тоже не вариант. Народ будет забывать менять ветку, и я свихнусь конфликты фиксить.
Лучше будем готовить людей острожно: 
-На первом году можно было вообще без git жить;
-Первая часть второго года - одна ветка, но уже на гитхабе;
-Вторая часть второго года - уже крутой проект, много веток, много разработчиков

**Comment by nm17** [comment]
Ок. Но можно будет копировать у других. Надо как-то разграничить права. 

Edit: если конечно копировать запрещено :relaxed: .

**Comment by nm17** [comment]
@mabramovsd Кстати, слышал про докер. Говорят удобная штука. Можете объяснить что это? Как я понял это типо трависа но на отдельно выделенной машине.

Edit: а проект для ардуино и что это за проекты вообще?

**Comment by nm17** [comment]
> свихнусь конфликты фиксить

https://help.github.com/articles/about-protected-branches/

**Comment by nm17** [comment]
master-center, master-zavol, ... - protected
Все остальные - обычные.

**Comment by mabramovsd** [comment]
1) Ок. Но можно будет копировать у других. Надо как-то разграничить права. Если конечно копировать запрещено :relaxed: .
-Копировать не глядя бессмысленно: проекты похожие, но неодинаковые - тупо названия переменных не совпадут. К тому же по истории коммитов очень легко найти воришку. А подглядывать можно (чтобы подглядеть придется научиться лазить по гитхабу, а это само по себе развивает :) )

2) Кстати, слышал про докер. Говорят удобная штука. Можете объяснить что это? 
-У меня сложилось впечатление, что это действительно аналог travis, который ставишь к себе на комп и радуешься. Но не пользовался, только по статьям на хабре могу судить

3) Про защищенные ветки. В принципе, да, добьемся того же самого. Но по смыслу в двух группах не одинаковые проекты. Похожие, но не одинаковые. Грубо говоря, в центре собирают самолет Boeing, в Заволжье Ту-104. Не объединять же разработку двух разных самолетов в один репозиторий.
А защищенные ветки подходят для разработки двух версий проектов - ну там 4.7 (мелкие изменения) и 5.0 (большие изменения) если сейчас актуальная 4.6.

4) О том, что это за проекты. Это первая часть плана на второй год обучения. Всё тот же C++, все проекты - графические редакторы. Их, кстати, не 2, а 6 разных. Ну а при небольшом применения фантазии примерно 10. Сперва месяц-полтора работаем с "прототипами" и решаем простые задачки на повторение, но совместно. То есть нет персонального проекта Даниила Николаева: сегодня тебе достается автосервис, завтра дизайн интерьера, послезавтра football manager. Это неприятно, но командная работа необходима

Когда с повторением закончено, будет вторая часть. Сперва всей толпой собираемся и говорим: football manager - фигня, давайте дальше создавать фоторобот (или автосервис, или карту города и т.д.). И пишем фоторобот. Он уже разбит на 30 задач, каждый делает что-то свое, всё это уже в отдельных ветках. В результате должна получиться крутая программа с классами, десятками файлов с исходным кодом, возможностью нарисовать любое лицо и сохраниться результат а VK.

Я в VK в группе "Инженерки" подробнее писал. Если есть вопросы, можно будет 9 сентября обсудить. В любом случае с первогодниками встречаюсь, можно и второгодникам прийти. Ну или у вас отдельное собрание будет

**Comment by nm17** [comment]
@mabramovsd Спасибо за ответ, на счет прав: теперь у нас есть команды center1 ,center2 и тд. 

Можете также добавить как админа ко всем организациям. Есть пару идей как оформить все это.

**Comment by nm17** [comment]
@mabramovsd Также придется научиться git-у полностью, чтобы небыло конфликтов между пулл реквестами.

Для этого нашел хороший сайт: https://githowto.com/ru

Там все хорошо написано и объяснено. Думаю что особо долго не займет.
